### ISSUE TITLE
Potential additional features

### ISSUE THREAD

**Issue by sjurgemeyer** [freitass/todo.txt-vim#16]
I have several functions that I created for my own convenience that may fit into this plugin.  If any or all of these fit into the spirit of this plugin and I can create a PR.

https://github.com/sjurgemeyer/vim-todo.txt-plugin

**Comment by AnderRasoVazquez** [comment]
Date sorting would be nice to have.

**Comment by freitass** [comment]
Added sorting on date feature. Thanks for the suggestion!
I'm closing this issue to prevent it from becoming the "default gateway" for new feature requests. :)

**Comment by AnderRasoVazquez** [comment]
When a task has a high priority it should appear at the top of the list. so a close in time task should appear at the top and further tasks lower. This update reorders them at the contrary =)

**Comment by freitass** [comment]
What do you mean by "close in time"? Currently, the most recent task ends up on top of the list.

**Comment by freitass** [comment]
I mean, taking into account the first date on each line, the date which is most in the future is on top.

**Comment by AnderRasoVazquez** [comment]
That's what I mean, future tasks are on the top and I think they shuld be like this:
2015
2016
2017
That way you can start completing future tasks on order, doesn't make much sense scrolling down to see what is will due sooner.and completing them down to up.

**Comment by AnderRasoVazquez** [comment]
Now the sorting is right but they appear behind other not dated tasks. This is what I meaned earlier:
2015
2016
2017
a task without date
a task without date

**Comment by freitass** [comment]
Just pushed the change. Please, check again!

**Comment by AnderRasoVazquez** [comment]
Now works perfectly! Thanks for maintaining this plugin. I use it everyday =D
