### ISSUE TITLE
question about shortcuts / bindings

### ISSUE THREAD

**Issue by aurisnoctis** [freitass/todo.txt-vim#27]
First of all: thank you very much for this vim customization!

I like the idea of shortcuts a lot, but I am not sure how to use them. For instance I tried the option `<leader>-k : Increase the priority of the current line`. My `leader` is usually `:`. For instance, when I want to save a file and then exit, I type `:wq`. So I opened my todo.txt and typed `:k`, also tried `:-k`, but it returns `E471: Argument required`.

I also tried marking the whole line before applying this, but no luck.

Any help is greatly appreciated - thanks.

Update:
My <leader> key was not defined, so I added `let mapleader=","`to my .vimrc. Then I tried `,k` and `,-k` in command mode, but still no success for me.

Update 2:
I tried `date<tab>` now in insert mode, and it results in exactly that verbatim, without inserting the date. So maybe something is not set up correctly - like permissions. But I do get the highlighting, so the add-on is in the right folder `~/.vim`.

Update 3:
Some of my other mappings from long ago were conflicting these mappings. So I temporarily moved my `.vimrc`, and then typed -- using the default map leader `\` -- `\k` in command mode. Still no luck.

**Comment by invecup** [comment]
Make sure that your cursor is on the correct line and that the line has a priority set already. Increasing/decreasing doesn't work with no priority on the line.

**Comment by freitass** [comment]
@aurisnoctis I don't think it's a good idea to use `:` as your `<leader>` key, since it's used to enter 'command-line' mode. Take a look at `:h <leader>` for more info. Moreover, you need to be in 'normal' mode for the commands to work properly.

**Comment by aurisnoctis** [comment]
@freitass Agreed. I had never used a self-defined mapleader before, just shortcuts like <code>:map <F5> i!mz_hr_<C-R>=strftime("%Y%m%d")<CR>+<Esc></code> to add time stamps to my Fortran files. I looked at <code>:h leader </code> and now re-defined <code>:let mapleader = ","</code> again.

I open a todo.txt file, stay in normal mode, go to a line with priority <code>(B)</code>, type <code>,-k</code> and all that happens is the cursor going up when I hit <code>-</code> and once more when I hit <code>k</code> (as expected without special shortcuts). Obviously, I have no clue how to apply the <code>\<localleader\>-k</code> command stated in the manual.

troubleshooting:
- looked into <code>ftplugin/todo.vim</code>, and the <code>-</code> in the todo.txt-vim description seems to only mean to press the leader and the following character together. Ok. Now, pressing <code>,k</code> one after the other or together moves the cursor up one line, priority is unchanged.
- typing <code>:let mapleader</code> yields <code>mapleader              ,</code>, so the leader setting seems ok
- my <code>~./vim</code> directory has the following contents: README.markdown  doc  done.txt  ferret.vim  fortran.vim  ftdetect  ftplugin  mysyntax.vim  plugin  syntax  todo.txt
- I had an entry <code>nnoremap , g0ze</code> in my .vimrc before that had worked fine. I commented it out after installing todo.txt-vim to avoid interference with the mapleader <code>,</code> that I defined
- Maybe <code>Note that the value of "mapleader" is used at the moment the mapping is defined.  Changing "mapleader" after that has no effect for already defined mappings.</code> from the vim help is related to my issues? Or other mappings?

Any help greatly appreciated.

**Comment by freitass** [comment]
@aurisnoctis that hyphen in the documentation is misleading, it is not included in the mapping. I will be fixing that soon.

All of the mappings were changed to use <localleader> instead of <leader> because that's the recommended policy for filetype plugins (to avoid collision with mappings defined by global plugins). To set your <localleader> you do `let maplocalleader = ,`. You can set the same key for both <leader> and <localleader>. Please, see `:h <localleader>` for more info.

**Comment by aurisnoctis** [comment]
@freitass Thank you for getting back to me.

I added Edit2 above, probably at the same time as your comment, and had defined <code>:let maplocalleader = ","</code> as well. I now also updated all todo.txt-vim files in my <code>~/.vim</code> directory and saw the change in <code>~/.vim/ftplugin/todo.vim</code> to <code>\<localleader\>k :call todo#txt#prioritize_decrease()</code>. Typing <code>,k</code> still only moves the cursor one line up, as if there were no mapping at all, plain vi behavior.

I suspect my vim doesn't know about the todo.txt-vim files available in <code>~/.vim</code>. For the other files in that directory, like <code>fortran.vim</code> I have a special entry in my <code>~/.vimrc</code> that says <code>let mysyntaxfile = "~/.vim/mysyntax.vim"</code>. In that file, there is are two lines
<pre>au BufRead,BufNewFile *.f set filetype=fortran
au! Syntax fortran source ~/.vim/fortran.vim</pre>

Could this be the reason? A missing hint to my vim to actually use it instead of just copying the files into <code>~/.vim</code>?

**Comment by freitass** [comment]
@aurisnoctis Check if the mapping is correct by opening a todo.txt file and checking the output of `:map ,k` (remember to change `,` with your <localleader>, mine is `\`). The result should be:

    v  \k          &@:call todo#txt#prioritize_decrease()<CR>
    n  \k          &@:call todo#txt#prioritize_decrease()<CR>

Also, make sure you have the latest version of this plugin, the function `TodoTxtPrioritizeDecrease()` has been renamed. I strongly recommend using a plugin manager (such as Vundle) if you are not using one yet.

**Comment by aurisnoctis** [comment]
I now deleted everything in my <code>~/.vim</code> directory except for your files (current version here). I deleted everything in my <code>~/.vimrc</code> except for the following 3 lines
<pre>:let mapleader=","
:let maplocalleader = ","
:nnoremap <localleader>d dd
</pre>

the cursor still just goes one line up then pressing <code>,k</code> in short sequence. Trying other todo.txt-vim shortcuts, they all behave as if without todo.txt-vim. My own shortcut in <code>~/.vimrc</code> (3rd line above) works, also changing it to for instance <code>:nnoremap <localleader>d iHELLO</code>).

Re your comment above, yes, exactly, the todo.txt-vim mapping is not known to my vim, just my own definitions from <code>~/.vimrc</code>:
<pre>
:map ,k No mapping found
:map \k No mapping found
:map ,d n  ,d          * dd
</pre>

How can I make my vim see your configuration files?

**Comment by aurisnoctis** [comment]
I again added the line <code>let mysyntaxfile = "~/.vim/mysyntax.vim"</code> to my <code>~/.vimrc</code> file. In the file <code>~/.vim/mysyntax.vim</code>, I then added the lines

<pre> au BufRead,BufNewFile todo.txt set filetype=todo
au! Syntax todo source ~/.vim/ftplugin/todo.vim</pre>

to tell my vim where to find the definitions (analog to what I had before for fortran highlighting for example).

THIS WORKS. YAY. <code>,k</code> and <code>date \<tab\></code> and a couple of other things I tested.

So is there a part of the documentation missing? Or is there a part of todo.txt-vim configuration that should have done that configuration above for me?

**Comment by freitass** [comment]
The file `~/.vim/ftdetect/todo.vim` inside you user runtime directory does exactly what you did manually, which is setting the filetype "todo" for todo.txt files. Vim should source the file `~/.vim/ftplugin/todo.vim` automatically for all files with filetype "todo". The only thing I can imagine is that you have an old version of vim, but I can't tell in which version the behavior I just described was introduced. One way or another, I'm glad that you figured out a way to make it work!

**Comment by aurisnoctis** [comment]
@freitass My vim version self-confesses the following
<pre>VIM - Vi IMproved 7.3 (2010 Aug 15, compiled May  4 2012 04:22:36)
Included patches: 1-429
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by buildd@
Huge version with GTK2-GNOME GUI.</pre>

Thanks for the hint - I didn't know there was a central infrastructure in vim to recognize file type. Here is the documentation for the file type detection in vim http://vimdoc.sourceforge.net/htmldoc/filetype.html. It says <code>filetype.txt  For Vim version 7.3.  Last change: 2008 Jul 15</code> - strange that my vim is still version 7.3 even though from 2 years later ...

I am just glad it works. So it's just the same I did for Fortran highlighting, just with your specific <code>~/.vim/ftplugin/todo.vim file</code> and instructions as above. :+1:
