### ISSUE TITLE
Bad sorting with + inside todo text

### ISSUE THREAD

**Issue by naught101** [freitass/todo.txt-vim#30]
```
(B) Linear regression Rnet=Qh+Qle. +cons_emp_model
(A) Review key questions. +benchmarking
(B) simple model first +cons_emp_model
```

This is the sorted result with `<leader>s+`.  the +Qle is not a project, and so it shouldn't be included in the sorting. A project needs to have a space before it, according to the spec, and in this case it doesn't. Bad regex?

**Comment by naught101** [comment]
This fix is wrong: `/.\{-}\(^\|\W\)\ze+/` the non-greedy match doesn't work, although I'm not sure why. And, it matches a + with a space after it.

This works `/^\(.\{-}\s\|\s*\)+\ze\w` - that is, match either some leading non-greedy text with following whitespace, or match some leading whitespace. I think `\s` is better than `\W`, because projects like `_+blah` don't make much sense, I suspect it'd be better to exclude them.

**Comment by freitass** [comment]
I tried you suggestion but it didn't work here either. There are some character escaping issues when we put the regex on the ftplugin file and I think they are fixed now. I also added some tests so it will become harder to repeat the same mistakes in the future (if there are tests for them, of course).
