### ISSUE TITLE
Question about the documentation

### ISSUE THREAD

**Issue by ultrablue** [freitass/todo.txt-vim#38]
Hey:
This is a really useful tool. Thank you!

My question is this: the documentation says:
date<tab> (Insert mode) Insert the current date
Does that mean:
Enter Insert mode.
Type 'date' followed by a tab.

Thanks,
Greg

**Comment by freitass** [comment]
Hi Greg,

Your interpretation is correct, typing `date` and then a <kbd>Tab</kbd> will insert today's date in the same format as the one used for task creation dates (and the date will be inserted under the cursor). Do you observe a different behavior?

Leandro

**Comment by ultrablue** [comment]
Hi, Leandro:

Sorry for the delay on this.

Oops. I was about to say that I am observing a different behavior, but perhaps I was waiting too long between finishing `date` and starting `Tab`. If I'm a little quicker it appears to work fine. That's with a recent version of MacVim.

Thanks!
Greg
