### ISSUE TITLE
Error message about python

### ISSUE THREAD

**Issue by ernestorenanche** [freitass/todo.txt-vim#49]
Hello,

My vim has been built with python3 but not with python. Here are the relevant output of `vim --version`: `-python +python3`.
However I get a error message at start-up and the feature regarding overdue dates does not work.
I think it should work with python 3 and the line 53 in todo.vim should be replaced by `if has('python') || has('python3')`.

Best.

**Comment by freitass** [comment]
Hello @ernestorenanche, did you try that change on your machine? I'm not having much time these days to set up an environment to test this scenario. If you tell me that it works I'll push the change (even better would be you submitting a patch 😄 ). Thanks a lot!

**Comment by ernestorenanche** [comment]
Ok in fact I rewrite the regex function in plain vimscript. This way, it can work even without python. Will probably patch it this weekend.

**Comment by fievel** [comment]
See my correction in #50
