### ISSUE TITLE
Python Code for checking due dates incorrect for November

### ISSUE THREAD

**Issue by as-kholin** [freitass/todo.txt-vim#56]
Issue is with [before.py, Line 47](https://github.com/freitass/todo.txt-vim/blob/master/syntax/python/dateregex/dateregex/before.py#L47).

last_month_day = str((date(int(year), **(int(month) + 1) % 12**, 1) + - date.resolution).day)
This would never work in November, as you would get a '0' instead of a '12', and there is no 0 month.

If this is adjusted to (int(month) % 12) + 1, then it corrects the issue with November, and matches all other month cases.

**Comment by victal** [comment]
Hello, 
Coincidentally, I sent a PR about the same problem earlier (https://github.com/freitass/todo.txt-vim/pull/55). 

One can use the plugin from that branch (or fix it locally since it's a small change) while it is not merged.

**Comment by freitass** [comment]
Just merged the PR. Thanks guys!
