### ISSUE TITLE
color coding of @fields? 

### ISSUE THREAD

**Issue by tpaixao** [freitass/todo.txt-vim#63]
at least in my vim, lists or contexts (the ones starting with @) have the same color as tags or projects (+fields)...

any ideas?

**Comment by tpaixao** [comment]
Well, I ended up changing the syntax/todo.vim  file so that the two render in different colors:

Both TodoProject and TodoContext were set to Special. I changed TodoContext to String. 
Would be happy to push that change if anyone is interested

**Comment by Jazztache** [comment]
I would something like this to become default.
