### ISSUE TITLE
Respect todo.txt format when inserting dates

### ISSUE THREAD

**Issue by neoascetic** [freitass/todo.txt-vim#9]
`<leader>-d` and `<leader>-D` must insert dates in the beginning of the line, not right under cursor

**Comment by thperret** [comment]
sorry to dig up this issue but according to the todo.txt [specifications](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format#rule-1-if-priority-exists-it-always-appears-first) the priority should always be first and creation date should be right after priority separated by a space.

**Comment by freitass** [comment]
Thanks for pointing that out. Now it's fixed!

**Comment by thperret** [comment]
Just tested and everything's fine! Thanks!
